### PR TITLE
updates with node and line styling

### PR DESCRIPTION
**Pull request by morandd**
Thanks for this great component.

I've added some options around node and line styling and scaling.

### CODE REVIEW

**Comment by vasturiano** [comment]
@morandd thanks for the PR. I like your additional features! There are however some code conflicts with my latest version. Could you fix the conflicts and push an update?

**Comment by morandd** [comment]
Hi,

I took a look through the diff but I can't see what conflicts you refer to? Looking at the diff in index.js for this pull request, I think all the changes there are correct, ie. the changes I am proposing. And I think same for the readme. The two files in dist/ get rebuilt anyway so we can ignore them. The index.html should be trivial to resolve, it's a small file.

Sorry I am not so clever with git. As I understand it, I forked your repo, then we both made changes at the same time, and now when I try and merge back into yours, there is a conflict - right? But whats strange is that when I look at the diff in this pull request, I only see my changes against your original index.js; I dont see any new code you introduced yesterday. 

To solve this: I will ask some colleagues if they can help me understand the git conflict resolution. Or, I think you can do it, since you are the owner of your repo. 

Sorry for the headache! I wish I were more clever with git and could do this more smoothly.

**Comment by morandd** [comment]
Ah - when I look at the diff in this pull request I don't see your new "alphaDecay". Something's gone pear-shaped. I'll look into it.

**Comment by morandd** [comment]
Maybe one way is you send me a pull request, so I can pull in your changes.

Then I will worry about resolving the diffs and merging.

Then I will send you back a PR with the merged code.

**Comment by vasturiano** [comment]
Hi @morandd, to pull in the latest changes into your forked repo you should sync it. 
This may be of help: https://help.github.com/articles/syncing-a-fork/

**Pull request closed without merging**
